### ISSUE TITLE
Feature: User can create a Deck

### ISSUE THREAD

**Issue by Raphael-Cruzado** [Raphael-Cruzado/LF-Final-Project#1]
## ⚙️ User Can Create a Deck

> ##### What capability will users have when this feature is merged?

 Adds a new class/deck to user database.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Once the user hits the landing page, they have the option to create a new deck and give it a name.
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/57853350/171067913-ddf5f092-f7b0-45a0-bad0-3e9e2482c7d8.png)
![image](https://user-images.githubusercontent.com/57853350/171067971-90fac39a-c01e-43c8-a710-590ad6c899e3.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [ ] Update `schema.sql` to Final Project

### ☁️ Server

- [ ] Create an endpoint POST /api/decks to create a new deck in the data base
- [ ] Update `server/index.js` to Final Project
- [ ] Test with HTTPie
- [ ] Handle all errors and respond to the client

### ⚡ Client

- [ ] Create a component to create a modal on click
- [ ] Create a component to create a new deck entry on submit ('continue')
- [ ] Create component to add data to flashcards.sql
- [ ] Create a component to lead user to newly created Deck

### 🧑‍⚕️ Clean Up

- [ ] ... 
- [ ] ...
- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
