### ISSUE TITLE
Feature: User can create Cards 

### ISSUE THREAD

**Issue by Raphael-Cruzado** [Raphael-Cruzado/LF-Final-Project#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

After deck is created, user can start creating cards on the deck

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

After modal submit user is lead to the edit page where users can add flash flashcards, in later features users will be able to edit and delete flashcards as well on the same page

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/57853350/171070494-013e65be-df08-47dc-b382-14a1f7014182.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [ ] Update `schema.sql` to ...
- [ ] Update `data.sql` to ...

### ☁️ Server

- [ ] Create an endpoint POST /api/cards to create a new card in the data base
- [ ] Update `server/index.js` to Final Project
- [ ] Test with HTTPie
- [ ] Handle all errors and respond to the client

### ⚡ Client

- [ ] Create a component to add card to deck

### 🧑‍⚕️ Clean Up

- [ ] ... 
- [ ] ...
- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
